# External DNS for Automatic DNS Management
# This will automatically create/update DNS records in Cloudflare for your ingress resources

apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
  labels:
    name: external-dns
---
# Service Account for External DNS
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: external-dns
---
# Cluster Role - Permissions for External DNS
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns
rules:
  - apiGroups: [""]
    resources:
      - services
      - endpoints
      - pods
      - nodes
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - networking.k8s.io
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - watch
      - list
---
# Cluster Role Binding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
  - kind: ServiceAccount
    name: external-dns
    namespace: external-dns
---
# Cloudflare API Token Secret Template
# DO NOT PUT YOUR ACTUAL TOKEN HERE - See deployment instructions below
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: external-dns
  annotations:
    # This secret will also be created in cert-manager namespace for SSL certificates
    kubernetes.io/description: "Cloudflare API Token for DNS management"
type: Opaque
stringData:
  api-token: "REPLACE_WITH_YOUR_TOKEN"  # This will be replaced during deployment
---
# Also create the secret in cert-manager namespace for SSL
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
  annotations:
    kubernetes.io/description: "Cloudflare API Token for SSL certificate DNS validation"
type: Opaque
stringData:
  api-token: "REPLACE_WITH_YOUR_TOKEN"  # This will be replaced during deployment
---
# External DNS Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: external-dns
  labels:
    app: external-dns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v0.14.0
        imagePullPolicy: IfNotPresent
        env:
          - name: CF_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: cloudflare-api-token-secret
                key: api-token
        args:
          - --source=service
          - --source=ingress
          - --provider=cloudflare
          - --domain-filter=isaiahmichael.com
          - --registry=txt
          - --txt-owner-id=external-dns-aks
          - --txt-prefix=external-dns-
          - --log-level=debug
          - --interval=30s
          - --events
        ports:
        - containerPort: 7979
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "100Mi"
            cpu: "100m"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
---
# Service for External DNS (optional, for monitoring)
apiVersion: v1
kind: Service
metadata:
  name: external-dns
  namespace: external-dns
  labels:
    app: external-dns
spec:
  selector:
    app: external-dns
  ports:
  - port: 7979
    targetPort: http
    protocol: TCP
    name: http
