apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-classifier
  namespace: app
  labels:
    app: image-classifier
spec:
  replicas: 3
  selector:
    matchLabels:
      app: image-classifier
  template:
    metadata:
      labels:
        app: image-classifier
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/health"
    spec:
      containers:
        - name: image-classifier
          image: acrrgdevuksouthisaiah4748.azurecr.io/fastapi-image-classifier:latest
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: image-classifier
  namespace: app
  labels:
    app: image-classifier
spec:
  selector:
    app: image-classifier
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: app
  annotations:
    # NGINX Ingress annotations
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    
    # Cert-manager for SSL certificates
    cert-manager.io/cluster-issuer: "letsencrypt-dns"
    
    # External DNS annotations - force target IP to LoadBalancer external IP
    external-dns.alpha.kubernetes.io/hostname: aks.isaiahmichael.com
    external-dns.alpha.kubernetes.io/target: "74.177.117.202"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - aks.isaiahmichael.com
      secretName: app-tls-secret
  rules:
    - host: aks.isaiahmichael.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: image-classifier
                port:
                  number: 80
