apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring-ingress
  namespace: monitoring
  annotations:
    # NGINX Ingress annotations
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: monitoring-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - Monitoring'
    
    # Cert-manager for SSL certificates
    cert-manager.io/cluster-issuer: "letsencrypt-dns"
    
    # External DNS annotations - force target IP to LoadBalancer external IP
    external-dns.alpha.kubernetes.io/hostname: prometheus.isaiahmichael.com,grafana.isaiahmichael.com
    external-dns.alpha.kubernetes.io/target: "74.177.117.202"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
    
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - prometheus.isaiahmichael.com
    - grafana.isaiahmichael.com
    secretName: monitoring-tls-secret
  rules:
  - host: prometheus.isaiahmichael.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus
            port:
              number: 9090
  - host: grafana.isaiahmichael.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grafana
            port:
              number: 3000
---
# Basic auth secret for monitoring (create with: htpasswd -c auth username)
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-auth
  namespace: monitoring
type: Opaque
data:
  auth: YWRtaW46JGFwcjEkSDY1dnFMNUckVy5qTDhIT2k2dE9mTy4yRGtoMzcv  # admin:admin (change this!)
---
# Additional Grafana configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
data:
  grafana.ini: |
    [server]
    root_url = https://grafana.isaiahmichael.com
    [security]
    admin_user = admin
    admin_password = admin123  # Change this!
    [auth.anonymous]
    enabled = false
